### ISSUE TITLE
Compilation error on openwrt 23.05

### ISSUE THREAD

**Issue by kuncy7** [gl-inet/home-assistant-on-openwrt#12]
Hi,

This error occurs when trying to compile on version 23.05:

```make[3]: Entering directory '/home/metium/openwrt/feeds/homeassistant/python-packages/python-ha-pycparser'
rm -f /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.built
touch /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.built_check
SHELL= flock /home/metium/openwrt/tmp/.pip.flock -c ' ARCH="x86_64" CC="gcc" CCSHARED="gcc -DPIC -fPIC" CXX="g++" LD="gcc" LDSHARED="gcc -shared" CFLAGS="-O2 -I/home/metium/openwrt/staging_dir/host/include -I/home/metium/openwrt/staging_dir/hostpkg/include -I/home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/include" CPPFLAGS="-I/home/metium/openwrt/staging_dir/host/include -I/home/metium/openwrt/staging_dir/hostpkg/include -I/home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/include -I/home/metium/openwrt/staging_dir/hostpkg/include/python3.11" LDFLAGS="-L/home/metium/openwrt/staging_dir/host/lib -L/home/metium/openwrt/staging_dir/hostpkg/lib -L/home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/lib -lpython3.11 -Wl,-rpath,/home/metium/openwrt/staging_dir/hostpkg/lib"  CARGO_HOME=/home/metium/openwrt/dl/cargo SETUPTOOLS_RUST_CARGO_PROFILE="release" PIP_CACHE_DIR="/home/metium/openwrt/dl/pip-cache" PIP_CONFIG_FILE=/dev/null PIP_DISABLE_PIP_VERSION_CHECK=1 /home/metium/openwrt/staging_dir/hostpkg/bin/pip3.11 install --no-binary :all: --progress-bar off --require-hashes  --requirement /home/metium/openwrt/feeds/packages/lang/python/host-pip-requirements/ply.txt  ' 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/metium/openwrt/feeds/packages/lang/python/host-pip-requirements/ply.txt'
make[3]: *** [Makefile:47: /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.built] Error 1
make[3]: Leaving directory '/home/metium/openwrt/feeds/homeassistant/python-packages/python-ha-pycparser'
time: package/feeds/homeassistant/python-ha-pycparser/compile#0.49#0.08#0.56
    ERROR: package/feeds/homeassistant/python-ha-pycparser failed to build.
make[2]: *** [package/Makefile:120: package/feeds/homeassistant/python-ha-pycparser/compile] Error 1
make[2]: Leaving directory '/home/metium/openwrt'
make[1]: *** [package/Makefile:114: /home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/metium/openwrt'
make: *** [/home/metium/openwrt/include/toplevel.mk:232: world] Error 2```

**Comment by kuncy7** [comment]
I am sorry, my mistake!

**Comment by kuncy7** [comment]
Close
